WARNING: autodoc: failed to import module 'ad9361'; the following exception was raised:
['Traceback (most recent call last):\n', '  File "/home/dator1/Documents/antsdr/env/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 269, in import_object\n    module = import_module(modname, try_reload=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/dator1/Documents/antsdr/env/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 175, in import_module\n    module = importlib.import_module(modname)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import\n', '  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 995, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed\n', '  File "/home/dator1/Documents/antsdr/libad9361-iio/bindings/python/ad9361.py", line 10, in <module>\n    from iio import _ContextPtr, _DevicePtr\n', "ImportError: cannot import name '_ContextPtr' from 'iio' (/home/dator1/Documents/antsdr/env/lib/python3.12/site-packages/iio.py)\n"] [autodoc.import_object]
